#!./venv/bin/python
from cleo import Application
from commands.run import RunCommand
from commands.test import TestCommand

app = Application()
app.add(RunCommand())
app.add(TestCommand())

if __name__ == '__main__':
    app.run()